#!/usr/bin/env bash


#####################################################
# Created by cryptopool.builders-OLD-VERSION for crypto use...
#####################################################
# Needs to be ran after the first reboot of the system after permissions are set
#####################################################

source /etc/functions.sh

sudo yiimp coin UNF delete
sudo yiimp coin DES delete
sudo yiimp coin KUMA delete
sudo yiimp coin MEME delete
sudo yiimp coin FOOT delete
sudo yiimp coin UMO delete
sudo yiimp coin G3N delete
sudo yiimp coin SHND delete
sudo yiimp coin WHIPPED delete
sudo yiimp coin FLY delete
sudo yiimp coin BUMBA delete
sudo yiimp coin EBG delete
sudo yiimp coin I0C delete
sudo yiimp coin CAPT delete
sudo yiimp coin PAK delete
sudo yiimp coin EUC delete
sudo yiimp coin GRE-OLD delete
sudo yiimp coin PR delete
sudo yiimp coin VGC delete
sudo yiimp coin CFC delete
sudo yiimp coin GAME delete
sudo yiimp coin FONZ delete
sudo yiimp coin DBIC delete
sudo yiimp coin TRUMP delete
sudo yiimp coin JIF delete
sudo yiimp coin EVIL delete
sudo yiimp coin EVO delete
sudo yiimp coin LTCR delete
sudo yiimp coin SANDG delete
sudo yiimp coin RICHX delete
sudo yiimp coin ADZ delete
sudo yiimp coin DGCS delete
sudo yiimp coin BOLI delete
sudo yiimp coin LGBTQ delete
sudo yiimp coin ZOOM delete
sudo yiimp coin YOC delete
sudo yiimp coin SIB delete
sudo yiimp coin OPES delete
sudo yiimp coin NKC delete
sudo yiimp coin MMXVI delete
sudo yiimp coin MBL delete
sudo yiimp coin KNC delete
sudo yiimp coin AR2 delete
sudo yiimp coin AND delete
sudo yiimp coin TROLL delete
sudo yiimp coin DNET delete
sudo yiimp coin DCR delete
sudo yiimp coin EGC delete
sudo yiimp coin MND delete
sudo yiimp coin BNT delete
sudo yiimp coin AMS delete
sudo yiimp coin INFX delete
sudo yiimp coin BSD delete
sudo yiimp coin HTC delete
sudo yiimp coin CZECO delete
sudo yiimp coin EDRC delete
sudo yiimp coin FTP delete
sudo yiimp coin OP delete
sudo yiimp coin CHAI delete
sudo yiimp coin REV delete
sudo yiimp coin PULSE delete
sudo yiimp coin XCT delete
sudo yiimp coin STS delete
sudo yiimp coin EC delete
sudo yiimp coin CYG delete
sudo yiimp coin VAL delete
sudo yiimp coin TBC delete
sudo yiimp coin CRBIT delete
sudo yiimp coin GMX delete
sudo yiimp coin HODL delete
sudo yiimp coin KLC delete
sudo yiimp coin BUZZ delete
sudo yiimp coin ADCN delete
sudo yiimp coin RBIES delete
sudo yiimp coin SEC delete
sudo yiimp coin XID delete
sudo yiimp coin BTCU delete
sudo yiimp coin WARP delete
sudo yiimp coin CPNC delete
sudo yiimp coin HIRE delete
sudo yiimp coin SLS delete
sudo yiimp coin XHI delete
sudo yiimp coin RADS delete
sudo yiimp coin BTP delete
sudo yiimp coin X2 delete
sudo yiimp coin HMP delete
sudo yiimp coin BRONZ delete
sudo yiimp coin RUBIT delete
sudo yiimp coin REP delete
sudo yiimp coin SPL delete
sudo yiimp coin CIONZ delete
sudo yiimp coin SCRT delete
sudo yiimp coin DEUR delete
sudo yiimp coin VOX delete
sudo yiimp coin CLUB delete
sudo yiimp coin SCOT delete
sudo yiimp coin FLOZ delete
sudo yiimp coin STATS delete
sudo yiimp coin HZDOGE delete
sudo yiimp coin WLC delete
sudo yiimp coin BST delete
sudo yiimp coin BITUSD delete
sudo yiimp coin BITCNY delete
sudo yiimp coin FNX delete
sudo yiimp coin APC delete
sudo yiimp coin XLM delete
sudo yiimp coin AGRS delete
sudo yiimp coin DROP delete
sudo yiimp coin AMP delete
sudo yiimp coin ANTI delete
sudo yiimp coin 1337 delete
sudo yiimp coin TRBO delete
sudo yiimp coin BIC delete
sudo yiimp coin SOIL delete
sudo yiimp coin OMNI delete
sudo yiimp coin CUBE delete
sudo yiimp coin BAC delete
sudo yiimp coin WOP delete
sudo yiimp coin FCT delete
sudo yiimp coin PRT delete
sudo yiimp coin CBIT delete
sudo yiimp coin NEU delete
sudo yiimp coin STEPS delete
sudo yiimp coin EXP delete
sudo yiimp coin BCY delete
sudo yiimp coin PRIME delete
sudo yiimp coin SHF delete
sudo yiimp coin SWING delete
sudo yiimp coin MI delete
sudo yiimp coin MACRO delete
sudo yiimp coin SC delete
sudo yiimp coin GCR delete
sudo yiimp coin MAPC delete
sudo yiimp coin GCC delete
sudo yiimp coin TX delete
sudo yiimp coin ETH delete
sudo yiimp coin CRE delete
sudo yiimp coin AEON delete
sudo yiimp coin GSY delete
sudo yiimp coin CHIP delete
sudo yiimp coin BTCHC delete
sudo yiimp coin AXIOM delete
sudo yiimp coin FUEL delete
sudo yiimp coin BIOS delete
sudo yiimp coin CPC delete
sudo yiimp coin HNC delete
sudo yiimp coin IBITS delete
sudo yiimp coin DIGS delete
sudo yiimp coin NOC delete
sudo yiimp coin MCZ delete
sudo yiimp coin BANX delete
sudo yiimp coin CPN delete
sudo yiimp coin SPRTS delete
sudo yiimp coin SPROUT delete
sudo yiimp coin NUKE delete
sudo yiimp coin 2BACCO delete
sudo yiimp coin FIC delete
sudo yiimp coin LFO delete
sudo yiimp coin VERSA delete
sudo yiimp coin MCAR delete
sudo yiimp coin CARB delete
sudo yiimp coin ZUR delete
sudo yiimp coin VAPE delete
sudo yiimp coin TALK delete
sudo yiimp coin RUM delete
sudo yiimp coin PPCD delete
sudo yiimp coin PHO delete
sudo yiimp coin P0001 delete
sudo yiimp coin NODE delete
sudo yiimp coin MRC delete
sudo yiimp coin ISO delete
sudo yiimp coin HANSA delete
sudo yiimp coin FX01 delete
sudo yiimp coin FRSH delete
sudo yiimp coin FIMK delete
sudo yiimp coin FAIL delete
sudo yiimp coin DRM delete
sudo yiimp coin DRK delete
sudo yiimp coin CV2 delete
sudo yiimp coin BTRHA delete
sudo yiimp coin ALCUREX delete
sudo yiimp coin BNX delete
sudo yiimp coin QUIT delete
sudo yiimp coin V delete
sudo yiimp coin PLC delete
sudo yiimp coin GRW delete
sudo yiimp coin DUO delete
sudo yiimp coin ANI delete
sudo yiimp coin CDC delete
sudo yiimp coin CX delete
sudo yiimp coin MARS delete
sudo yiimp coin SHA delete
sudo yiimp coin FETISH delete
sudo yiimp coin EXC delete
sudo yiimp coin BDSM delete
sudo yiimp coin OFF delete
sudo yiimp coin EMC delete
sudo yiimp coin BLZ delete
sudo yiimp coin CHAO delete
sudo yiimp coin CNO delete
sudo yiimp coin FUNK delete
sudo yiimp coin UNIC delete
sudo yiimp coin DUCK delete
sudo yiimp coin BSY delete
sudo yiimp coin SPN delete
sudo yiimp coin IPC delete
sudo yiimp coin $MINEZ delete
sudo yiimp coin $MINEW delete
sudo yiimp coin ADD delete
sudo yiimp coin $MINE delete
sudo yiimp coin FTCC delete
sudo yiimp coin GXG delete
sudo yiimp coin CIV delete
sudo yiimp coin TOP delete
sudo yiimp coin TTY delete
sudo yiimp coin NTC delete
sudo yiimp coin KIWI delete
sudo yiimp coin XPL delete
sudo yiimp coin XGR delete
sudo yiimp coin $$$ delete
sudo yiimp coin 66 delete
sudo yiimp coin MDC delete
sudo yiimp coin SVC delete
sudo yiimp coin DARK delete
sudo yiimp coin POP delete
sudo yiimp coin WSX delete
sudo yiimp coin DOT delete
sudo yiimp coin YOVI delete
sudo yiimp coin HXX delete
sudo yiimp coin CRPS delete
sudo yiimp coin BAM delete
sudo yiimp coin SJW delete
sudo yiimp coin GMCX delete
sudo yiimp coin SPX delete
sudo yiimp coin EXT delete
sudo yiimp coin TENNET delete
sudo yiimp coin KC delete
sudo yiimp coin BLUS delete
sudo yiimp coin XRA delete
sudo yiimp coin SPEC delete
sudo yiimp coin EA delete
sudo yiimp coin TAGR delete
sudo yiimp coin HAZE delete
sudo yiimp coin TAM delete
sudo yiimp coin POLY delete
sudo yiimp coin INDEX delete
sudo yiimp coin GENI delete
sudo yiimp coin BUCKS delete
sudo yiimp coin SPKTR delete
sudo yiimp coin GENE delete
sudo yiimp coin GRM delete
sudo yiimp coin DIBS delete
sudo yiimp coin GTFO delete
sudo yiimp coin FUTC delete
sudo yiimp coin XVI delete
sudo yiimp coin GLOBE delete
sudo yiimp coin SMSR delete
sudo yiimp coin CIRC delete
sudo yiimp coin WOC2 delete
sudo yiimp coin NODX delete
sudo yiimp coin ERC delete
sudo yiimp coin SEN delete
sudo yiimp coin SAK delete
sudo yiimp coin EOC delete
sudo yiimp coin TRANSF delete
sudo yiimp coin GEN delete
sudo yiimp coin DRKT delete
sudo yiimp coin XCE delete
sudo yiimp coin XPH delete
sudo yiimp coin FIST delete
sudo yiimp coin DUB delete
sudo yiimp coin VAPOR delete
sudo yiimp coin ARPA delete
sudo yiimp coin BNB delete
sudo yiimp coin NANAS delete
sudo yiimp coin SEEDS delete
sudo yiimp coin OPTION delete
sudo yiimp coin DRA delete
sudo yiimp coin GLUCK delete
sudo yiimp coin EXB delete
sudo yiimp coin GREED delete
sudo yiimp coin MOIN delete
sudo yiimp coin VCOIN delete
sudo yiimp coin TWLV delete
sudo yiimp coin RDN delete
sudo yiimp coin PSY delete
sudo yiimp coin ECC delete
sudo yiimp coin SNRG delete
sudo yiimp coin ADC delete
sudo yiimp coin CREVA delete
sudo yiimp coin VCN delete
sudo yiimp coin 32BIT delete
sudo yiimp coin XNA delete
sudo yiimp coin TWERK delete
sudo yiimp coin CS delete
sudo yiimp coin GENIUS delete
sudo yiimp coin PRE delete
sudo yiimp coin NICE delete
sudo yiimp coin CORG delete
sudo yiimp coin DB delete
sudo yiimp coin EQM delete
sudo yiimp coin FADE delete
sudo yiimp coin SED delete
sudo yiimp coin SKB delete
sudo yiimp coin TNG delete
sudo yiimp coin ARB delete
sudo yiimp coin DCC delete
sudo yiimp coin PTA delete
sudo yiimp coin MRB delete
sudo yiimp coin BTA delete
sudo yiimp coin GRT delete
sudo yiimp coin AST delete
sudo yiimp coin BA delete
sudo yiimp coin KRAK delete
sudo yiimp coin M1 delete
sudo yiimp coin 16BIT delete
sudo yiimp coin TB delete
sudo yiimp coin BIT16 delete
sudo yiimp coin CLV delete
sudo yiimp coin SHELL delete
sudo yiimp coin LIMX delete
sudo yiimp coin BTI delete
sudo yiimp coin FSN delete
sudo yiimp coin TKT delete
sudo yiimp coin FCS delete
sudo yiimp coin VTN delete
sudo yiimp coin EPC delete
sudo yiimp coin PKB delete
sudo yiimp coin GAM delete
sudo yiimp coin ISL delete
sudo yiimp coin VIRAL delete
sudo yiimp coin UTLE delete
sudo yiimp coin PNC delete
sudo yiimp coin GOAT delete
sudo yiimp coin EPY delete
sudo yiimp coin CTO delete
sudo yiimp coin SPC delete
sudo yiimp coin GRAV delete
sudo yiimp coin GPH delete
sudo yiimp coin UNIT delete
sudo yiimp coin BUB delete
sudo yiimp coin BTX delete
sudo yiimp coin TDFB delete
sudo yiimp coin SPHR delete
sudo yiimp coin GUM delete
sudo yiimp coin XMS delete
sudo yiimp coin XSEED delete
sudo yiimp coin XNX delete
sudo yiimp coin XTP delete
sudo yiimp coin DOX delete
sudo yiimp coin QTZ delete
sudo yiimp coin UNAT-skein delete
sudo yiimp coin AIB delete
sudo yiimp coin GRAM delete
sudo yiimp coin SIGU delete
sudo yiimp coin BLITZ delete
sudo yiimp coin NIRO delete
sudo yiimp coin HUGE delete
sudo yiimp coin 7 delete
sudo yiimp coin DRZ delete
sudo yiimp coin LUX delete
sudo yiimp coin UIS-qubit delete
sudo yiimp coin UIS-skein delete
sudo yiimp coin SLING delete
sudo yiimp coin COV delete
sudo yiimp coin NTRN delete
sudo yiimp coin CTK delete
sudo yiimp coin CF delete
sudo yiimp coin CGN delete
sudo yiimp coin ACP delete
sudo yiimp coin OK delete
sudo yiimp coin 8BIT delete
sudo yiimp coin IEC delete
sudo yiimp coin P7C delete
sudo yiimp coin HZT delete
sudo yiimp coin LEA delete
sudo yiimp coin GIZ delete
sudo yiimp coin ETRUST delete
sudo yiimp coin XPRO delete
sudo yiimp coin TRON delete
sudo yiimp coin DECR delete
sudo yiimp coin RICE delete
sudo yiimp coin STP delete
sudo yiimp coin NXE delete
sudo yiimp coin AECC delete
sudo yiimp coin PLANET delete
sudo yiimp coin FIRE delete
sudo yiimp coin ANAL delete
sudo yiimp coin MTLMC3 delete
sudo yiimp coin TWIST delete
sudo yiimp coin CRIME delete
sudo yiimp coin BTCR delete
sudo yiimp coin TEC delete
sudo yiimp coin KARMA delete
sudo yiimp coin TCX delete
sudo yiimp coin TAB delete
sudo yiimp coin NDOGE delete
sudo yiimp coin GIFT delete
sudo yiimp coin BBCC delete
sudo yiimp coin TRICK delete
sudo yiimp coin DGMS delete
sudo yiimp coin CCB delete
sudo yiimp coin OZC delete
sudo yiimp coin STK delete
sudo yiimp coin SIC delete
sudo yiimp coin EGG delete
sudo yiimp coin EKN delete
sudo yiimp coin MRP delete
sudo yiimp coin QORA delete
sudo yiimp coin PXL delete
sudo yiimp coin CRY delete
sudo yiimp coin URC delete
sudo yiimp coin ICN delete
sudo yiimp coin OCTO delete
sudo yiimp coin EUR delete
sudo yiimp coin CAD delete
sudo yiimp coin CC delete
sudo yiimp coin XEM delete
sudo yiimp coin SLFI delete
sudo yiimp coin 256 delete
sudo yiimp coin ICASH delete
sudo yiimp coin BTCRY delete
sudo yiimp coin XDB delete
sudo yiimp coin ZIRK delete
sudo yiimp coin CRAVE delete
sudo yiimp coin BITZ delete
sudo yiimp coin OMC delete
sudo yiimp coin PAY delete
sudo yiimp coin LDOGE delete
sudo yiimp coin RBT delete
sudo yiimp coin ASN delete
sudo yiimp coin MINE delete
sudo yiimp coin XAU delete
sudo yiimp coin XFC delete
sudo yiimp coin UNC delete
sudo yiimp coin XCO delete
sudo yiimp coin VOYA delete
sudo yiimp coin XVC delete
sudo yiimp coin WBB delete
sudo yiimp coin ECASH delete
sudo yiimp coin MTR delete
sudo yiimp coin NSR delete
sudo yiimp coin GSM delete
sudo yiimp coin PTY delete
sudo yiimp coin LYB delete
sudo yiimp coin SUP delete
sudo yiimp coin CIN delete
sudo yiimp coin DD delete
sudo yiimp coin SMAC delete
sudo yiimp coin GRID delete
sudo yiimp coin SLM delete
sudo yiimp coin LTS delete
sudo yiimp coin XTC delete
sudo yiimp coin DGORE delete
sudo yiimp coin BITB delete
sudo yiimp coin BEAN delete
sudo yiimp coin PEN delete
sudo yiimp coin NVCD delete
sudo yiimp coin XPD delete
sudo yiimp coin CBX delete
sudo yiimp coin CELL delete
sudo yiimp coin KOBO delete
sudo yiimp coin LQD delete
sudo yiimp coin XTR delete
sudo yiimp coin 10K delete
sudo yiimp coin MYST delete
sudo yiimp coin BTCS delete
sudo yiimp coin XPB delete
sudo yiimp coin CETI delete
sudo yiimp coin OMA delete
sudo yiimp coin CCC delete
sudo yiimp coin XFB delete
sudo yiimp coin OBS delete
sudo yiimp coin SOON delete
sudo yiimp coin GIG delete
sudo yiimp coin XAP delete
sudo yiimp coin XBC delete
sudo yiimp coin XCH delete
sudo yiimp coin XCN delete
sudo yiimp coin XCP delete
sudo yiimp coin XDP delete
sudo yiimp coin XUSD delete
sudo yiimp coin YACC delete
sudo yiimp coin 1CR delete
sudo yiimp coin ACH delete
sudo yiimp coin ADN delete
sudo yiimp coin BCN delete
sudo yiimp coin BELA delete
sudo yiimp coin C2 delete
sudo yiimp coin CGA delete
sudo yiimp coin CHA delete
sudo yiimp coin CNMT delete
sudo yiimp coin CYC delete
sudo yiimp coin DIEM delete
sudo yiimp coin DSH delete
sudo yiimp coin FLDC delete
sudo yiimp coin GAP delete
sudo yiimp coin GDN delete
sudo yiimp coin GEMZ delete
sudo yiimp coin GOLD delete
sudo yiimp coin GRS delete
sudo yiimp coin HIRO delete
sudo yiimp coin HZ delete
sudo yiimp coin JLH delete
sudo yiimp coin LTBC delete
sudo yiimp coin MAID delete
sudo yiimp coin MCN delete
sudo yiimp coin MIL delete
sudo yiimp coin MMC delete
sudo yiimp coin MMNXT delete
sudo yiimp coin MNTA delete
sudo yiimp coin MRS delete
sudo yiimp coin NBT delete
sudo yiimp coin NOXT delete
sudo yiimp coin NXTI delete
sudo yiimp coin PIGGY delete
sudo yiimp coin PRC delete
sudo yiimp coin RIC delete
sudo yiimp coin SJCX delete
sudo yiimp coin SQL delete
sudo yiimp coin SRCC delete
sudo yiimp coin SWARM delete
sudo yiimp coin UNITY delete
sudo yiimp coin WOLF delete
sudo yiimp coin XWC delete
sudo yiimp coin FSC2 delete
sudo yiimp coin RBR delete
sudo yiimp coin CSD delete
sudo yiimp coin XDE delete
sudo yiimp coin XPC delete
sudo yiimp coin DGD delete
sudo yiimp coin ARI delete
sudo yiimp coin XBS delete
sudo yiimp coin USDT delete
sudo yiimp coin GP delete
sudo yiimp coin CON delete
sudo yiimp coin EAGS delete
sudo yiimp coin NKA delete
sudo yiimp coin INCA delete
sudo yiimp coin XSP delete
sudo yiimp coin BCR delete
sudo yiimp coin BLK delete
sudo yiimp coin SBIT delete
sudo yiimp coin UIS delete
sudo yiimp coin HGC delete
sudo yiimp coin 2015 delete
sudo yiimp coin GMC delete
sudo yiimp coin VMC delete
sudo yiimp coin ggggg delete
sudo yiimp coin UCI delete
sudo yiimp coin EQX delete
sudo yiimp coin STR delete
sudo yiimp coin TAK delete
sudo yiimp coin TEK delete
sudo yiimp coin TES delete
sudo yiimp coin TGC delete
sudo yiimp coin TOR delete
sudo yiimp coin TRC delete
sudo yiimp coin UNB delete
sudo yiimp coin USDe delete
sudo yiimp coin XCR delete
sudo yiimp coin XJO delete
sudo yiimp coin XLB delete
sudo yiimp coin YAC delete
sudo yiimp coin YBC delete
sudo yiimp coin ZCC delete
sudo yiimp coin ZED delete
sudo yiimp coin ADT delete
sudo yiimp coin ASC delete
sudo yiimp coin BAT delete
sudo yiimp coin COL delete
sudo yiimp coin CPR delete
sudo yiimp coin CTM delete
sudo yiimp coin DBL delete
sudo yiimp coin DMC delete
sudo yiimp coin ELP delete
sudo yiimp coin FLAP delete
sudo yiimp coin GME delete
sudo yiimp coin LEAF delete
sudo yiimp coin LOT delete
sudo yiimp coin MEM delete
sudo yiimp coin MEOW delete
sudo yiimp coin MST delete
sudo yiimp coin RBBT delete
sudo yiimp coin RED delete
sudo yiimp coin TIPS delete
sudo yiimp coin TIX delete
sudo yiimp coin XNC delete
sudo yiimp coin ZEIT delete
sudo yiimp coin AC delete
sudo yiimp coin ACOIN delete
sudo yiimp coin AGS delete
sudo yiimp coin ALF delete
sudo yiimp coin ALN delete
sudo yiimp coin AMC delete
sudo yiimp coin ARG delete
sudo yiimp coin AUR delete
sudo yiimp coin BCX delete
sudo yiimp coin BEN delete
sudo yiimp coin BET delete
sudo yiimp coin BNCR delete
sudo yiimp coin BOST delete
sudo yiimp coin BQC delete
sudo yiimp coin BTB delete
sudo yiimp coin BTE delete
sudo yiimp coin BTG delete
sudo yiimp coin BUK delete
sudo yiimp coin CACH delete
sudo yiimp coin CAP delete
sudo yiimp coin CASH delete
sudo yiimp coin CGB delete
sudo yiimp coin CINNI delete
sudo yiimp coin CMC delete
sudo yiimp coin CNC delete
sudo yiimp coin CNL delete
sudo yiimp coin COMM delete
sudo yiimp coin COOL delete
sudo yiimp coin CRACK delete
sudo yiimp coin CRC delete
sudo yiimp coin CSC delete
sudo yiimp coin DEM delete
sudo yiimp coin DMD delete
sudo yiimp coin DRKC delete
sudo yiimp coin DT delete
sudo yiimp coin DVC delete
sudo yiimp coin EAC delete
sudo yiimp coin ELC delete
sudo yiimp coin EMD delete
sudo yiimp coin EZC delete
sudo yiimp coin FFC delete
sudo yiimp coin FLT delete
sudo yiimp coin FRAC delete
sudo yiimp coin FRK delete
sudo yiimp coin FST delete
sudo yiimp coin GDC delete
sudo yiimp coin GLC delete
sudo yiimp coin GLD delete
sudo yiimp coin GLX delete
sudo yiimp coin GLYPH delete
sudo yiimp coin GUE delete
sudo yiimp coin HBN delete
sudo yiimp coin HVC delete
sudo yiimp coin ICB delete
sudo yiimp coin IXC delete
sudo yiimp coin JKC delete
sudo yiimp coin KDC delete
sudo yiimp coin KGC delete
sudo yiimp coin LAB delete
sudo yiimp coin LGD delete
sudo yiimp coin LK7 delete
sudo yiimp coin LKY delete
sudo yiimp coin LTB delete
sudo yiimp coin LTCX delete
sudo yiimp coin LYC delete
sudo yiimp coin MED delete
sudo yiimp coin MNC delete
sudo yiimp coin MZC delete
sudo yiimp coin NAN delete
sudo yiimp coin NBL delete
sudo yiimp coin NEC delete
sudo yiimp coin NRB delete
sudo yiimp coin NRS delete
sudo yiimp coin NYAN delete
sudo yiimp coin OSC delete
sudo yiimp coin PHS delete
sudo yiimp coin Points delete
sudo yiimp coin PSEUD delete
sudo yiimp coin PTS delete
sudo yiimp coin PYC delete
sudo yiimp coin RT2 delete
sudo yiimp coin RYC delete
sudo yiimp coin SAT2 delete
sudo yiimp coin SBC delete
sudo yiimp coin SHLD delete
sudo yiimp coin SILK delete
sudo yiimp coin SMC delete
sudo yiimp coin SOLE delete
sudo yiimp coin SPA delete
sudo yiimp coin SPT delete
sudo yiimp coin SSV delete
sudo yiimp coin EMC2 delete
sudo yiimp coin GIMP delete
sudo yiimp coin GRC delete
sudo yiimp coin KRYP delete
sudo yiimp coin MIC delete
sudo yiimp coin MOTO delete
sudo yiimp coin MSC delete
sudo yiimp coin NIC delete
sudo yiimp coin NWO delete
sudo yiimp coin PLCN delete
sudo yiimp coin PROZ delete
sudo yiimp coin SONG delete
sudo yiimp coin SPUDS delete
sudo yiimp coin SQC delete
sudo yiimp coin VOXP delete
sudo yiimp coin VTX delete
sudo yiimp coin XRC delete
sudo yiimp coin XSX delete
sudo yiimp coin XVG delete
sudo yiimp coin DON delete
sudo yiimp coin FJC delete
sudo yiimp coin GCN delete
sudo yiimp coin GRN delete
sudo yiimp coin GUA delete
sudo yiimp coin HAM delete
sudo yiimp coin HEX delete
sudo yiimp coin IFC delete
sudo yiimp coin IRL delete
sudo yiimp coin KARM delete
sudo yiimp coin MINT delete
sudo yiimp coin MOON delete
sudo yiimp coin MTLMC delete
sudo yiimp coin NMC delete
sudo yiimp coin NYC delete
sudo yiimp coin ORB delete
sudo yiimp coin PAC delete
sudo yiimp coin PCC delete
sudo yiimp coin PHC delete
sudo yiimp coin PPC delete
sudo yiimp coin RC delete
sudo yiimp coin SXC delete
sudo yiimp coin TRL delete
sudo yiimp coin USD delete
sudo yiimp coin VTA delete
sudo yiimp coin XPM delete
sudo yiimp coin BURST delete
sudo yiimp coin LTCD delete
sudo yiimp coin CRAIG delete
sudo yiimp coin TIT delete
sudo yiimp coin BSTY delete
sudo yiimp coin GNS delete
sudo yiimp coin DCN delete
sudo yiimp coin PXI delete
sudo yiimp coin MLS delete
sudo yiimp coin ROS delete
sudo yiimp coin STV delete
sudo yiimp coin OPAL delete
sudo yiimp coin EXCL delete
sudo yiimp coin PYRA delete
sudo yiimp coin NET delete
sudo yiimp coin SEED delete
sudo yiimp coin PND delete
sudo yiimp coin GHC delete
sudo yiimp coin DOPE delete
sudo yiimp coin ONE delete
sudo yiimp coin BLEU delete
sudo yiimp coin BVC delete
sudo yiimp coin CAGE delete
sudo yiimp coin CDN delete
sudo yiimp coin CESC delete
sudo yiimp coin CLR delete
sudo yiimp coin CZC delete
sudo yiimp coin CHILD delete
sudo yiimp coin XQN delete
sudo yiimp coin RDD delete
sudo yiimp coin NXT delete
sudo yiimp coin BC delete
sudo yiimp coin MYR-qubit delete
sudo yiimp coin UTC delete
sudo yiimp coin 888 delete
sudo yiimp coin EFL delete
sudo yiimp coin DIME delete
sudo yiimp coin SLR delete
sudo yiimp coin WATER delete
sudo yiimp coin NLG delete
sudo yiimp coin GIVE delete
sudo yiimp coin WC delete
sudo yiimp coin NOBL delete
sudo yiimp coin BITS delete
sudo yiimp coin BLU delete
sudo yiimp coin OC delete
sudo yiimp coin THC delete
sudo yiimp coin ENRG delete
sudo yiimp coin SHIBE delete
sudo yiimp coin SFR delete
sudo yiimp coin NAUT delete
sudo yiimp coin VRC delete
sudo yiimp coin CURE delete
sudo yiimp coin SYNC delete
sudo yiimp coin BLC delete
sudo yiimp coin XSI delete
sudo yiimp coin XC delete
sudo yiimp coin XDQ delete
sudo yiimp coin MMXIV delete
sudo yiimp coin CAIX delete
sudo yiimp coin BBR delete
sudo yiimp coin HYPER delete
sudo yiimp coin CCN delete
sudo yiimp coin KTK delete
sudo yiimp coin MUGA delete
sudo yiimp coin VOOT delete
sudo yiimp coin BN delete
sudo yiimp coin XMR delete
sudo yiimp coin CLOAK delete
sudo yiimp coin CHCC delete
sudo yiimp coin BURN delete
sudo yiimp coin KORE delete
sudo yiimp coin RZR delete
sudo yiimp coin XDN delete
sudo yiimp coin MIN delete
sudo yiimp coin TECH delete
sudo yiimp coin GML delete
sudo yiimp coin TRK delete
sudo yiimp coin WKC delete
sudo yiimp coin QTL delete
sudo yiimp coin XXX delete
sudo yiimp coin AERO delete
sudo yiimp coin TRUST delete
sudo yiimp coin BRIT delete
sudo yiimp coin JUDGE delete
sudo yiimp coin NAV delete
sudo yiimp coin XST delete
sudo yiimp coin APEX delete
sudo yiimp coin ZET delete
sudo yiimp coin BTCD delete
sudo yiimp coin KEY delete
sudo yiimp coin NUD delete
sudo yiimp coin TRI delete
sudo yiimp coin PES delete
sudo yiimp coin ICG delete
sudo yiimp coin UNO delete
sudo yiimp coin ESC delete
sudo yiimp coin PINK delete
sudo yiimp coin IOC delete
sudo yiimp coin SDC delete
sudo yiimp coin RAW delete
sudo yiimp coin MAX delete
sudo yiimp coin LXC delete
sudo yiimp coin BOOM delete
sudo yiimp coin BOB delete
sudo yiimp coin UNAT delete
sudo yiimp coin MWC delete
sudo yiimp coin VAULT delete
sudo yiimp coin FC2 delete
sudo yiimp coin SSD delete
sudo yiimp coin BIG delete
sudo yiimp coin GB delete
sudo yiimp coin ROOT delete
sudo yiimp coin AXR delete
sudo yiimp coin RIPO delete
sudo yiimp coin FIBRE delete
sudo yiimp coin SHADE delete
sudo yiimp coin FLEX delete
sudo yiimp coin XBOT delete
sudo yiimp coin XCASH delete
sudo yiimp coin FLO delete
sudo yiimp coin NKT delete
sudo yiimp coin TTC delete
sudo yiimp coin CLAM delete
sudo yiimp coin VTR delete
sudo yiimp coin SUPER delete
sudo yiimp coin NOO delete
sudo yiimp coin XPY delete
sudo yiimp coin SMLY delete
sudo yiimp coin BCENT delete
sudo yiimp coin DS delete
sudo yiimp coin FAIR delete
sudo yiimp coin EVENT delete
sudo yiimp coin HUC delete
sudo yiimp coin CAT delete
sudo yiimp coin WDC delete
sudo yiimp coin BTM delete
sudo yiimp coin RMS delete
sudo yiimp coin ANC delete
sudo yiimp coin MEC delete
sudo yiimp coin MONA delete
sudo yiimp coin DGC delete
sudo yiimp coin BCF delete
sudo yiimp coin SYS delete
sudo yiimp coin ULTC delete
sudo yiimp coin CXC delete
sudo yiimp coin METAL delete
sudo yiimp coin PTC delete
sudo yiimp coin SPR delete
sudo yiimp coin CBR delete
sudo yiimp coin FIND delete
sudo yiimp coin AM delete
sudo yiimp coin FUD delete
sudo yiimp coin ERM delete
sudo yiimp coin VIA delete
sudo yiimp coin CKC delete
sudo yiimp coin BTS delete
sudo yiimp coin DEAF delete
sudo yiimp coin HIC delete
sudo yiimp coin BAY delete
sudo yiimp coin VIOR delete
sudo yiimp coin VPN delete
sudo yiimp coin MN delete
sudo yiimp coin EXE delete
sudo yiimp coin PFC delete
sudo yiimp coin GSX delete
sudo yiimp coin BRXv2 delete
sudo yiimp coin ACHK delete
sudo yiimp coin CRYPT delete
sudo yiimp coin HLC delete
sudo yiimp coin SWIFT delete
sudo yiimp coin ARCH delete
sudo yiimp coin BTC delete
sudo yiimp coin GAIA delete
sudo yiimp coin WWC delete
sudo yiimp coin XRP delete
sudo yiimp coin LMR delete
sudo yiimp coin MNE delete
sudo yiimp coin CRW delete
sudo yiimp coin VDO delete
sudo yiimp coin NOPE delete
sudo yiimp coin XWT delete
sudo yiimp coin DTC delete
sudo yiimp coin SMBR delete
sudo yiimp coin HYP delete
sudo yiimp coin QBK delete
sudo yiimp coin CENT delete
sudo yiimp coin BLOCK delete
sudo yiimp coin CATC delete
sudo yiimp coin SCSY delete
sudo yiimp coin GUN delete
sudo yiimp coin ABY delete
sudo yiimp coin BALLS delete
sudo yiimp coin QSLV delete
sudo yiimp coin U delete
sudo yiimp coin BYC delete
sudo yiimp coin BUN delete
sudo yiimp coin ZER delete
sudo yiimp coin ZNY delete
sudo yiimp coin MRY delete
sudo yiimp coin CANN delete
sudo yiimp coin POT delete
sudo yiimp coin TAG delete
sudo yiimp coin DOGE delete
sudo yiimp coin RBY delete
sudo yiimp coin NOTE delete
sudo yiimp coin LTC delete
sudo yiimp coin NVC delete
sudo yiimp coin 42 delete
sudo yiimp coin JBS delete
sudo yiimp coin LSD delete
sudo yiimp coin J delete
sudo yiimp coin SLG delete
sudo yiimp coin VIK delete
sudo yiimp coin RPC delete
sudo yiimp coin XG delete
sudo yiimp coin DP delete
sudo yiimp coin MARYJ delete
sudo yiimp coin XMG delete
sudo yiimp coin RUBLE delete
sudo yiimp coin XCLD delete
sudo yiimp coin 007 delete
sudo yiimp coin BSC delete
sudo yiimp coin SKC delete
sudo yiimp coin LOG delete
sudo yiimp coin DRP delete
sudo yiimp coin CHC delete
sudo yiimp coin FLAX delete
sudo yiimp coin BOD delete
sudo yiimp coin HEDG delete
sudo yiimp coin ILM delete
sudo yiimp coin MYR delete
sudo yiimp coin CYP delete
sudo yiimp coin DASH delete
sudo yiimp coin ZRC delete
sudo yiimp coin GEO delete
sudo yiimp coin AMBER delete
sudo yiimp coin BTQ delete
sudo yiimp coin HTML5 delete
sudo yiimp coin HAL delete
sudo yiimp coin NEOS delete
sudo yiimp coin XAI delete
sudo yiimp coin DGB delete
sudo yiimp coin MDT delete
sudo yiimp coin MUE delete
sudo yiimp coin SRC delete
sudo yiimp coin QRK delete
sudo yiimp coin PXC delete
sudo yiimp coin FTC delete
sudo yiimp coin URO delete
sudo yiimp coin UFO delete
sudo yiimp coin VTC delete
sudo yiimp coin XDC delete
sudo yiimp coin START delete
sudo yiimp coin IDC delete
sudo yiimp coin a delete
sudo yiimp coin b delete
sudo yiimp coin c delete
sudo yiimp coin d delete

# Prevents error when trying to log in to admin panel the first time...

sudo touch $STORAGE_ROOT/yiimp/site/log/debug.log
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/.
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/debug.log

# Delete me no longer needed after it runs the first time

sudo rm -r $STORAGE_ROOT/yiimp/first_boot.sh
cd $HOME/multipool/yiimp_single
